### ISSUE TITLE
Demo not working on Bjs website

### ISSUE THREAD

**Issue by antonymarion** [andybeaulieu/BingWebGL#1]
Hi,

http://babylonbing.azurewebsites.net/

There seems to be an issue with the demo (credentials denied or suspended).

With the source code on github as well I got a weird syntax error on index.css:1:1 

Do you have any idea?

**Comment by andybeaulieu** [comment]
Yeah, apparently the Demo got too many requests for a free Bing API license, so it was shut down :( I'll see if I can get a new key.

As far as running the demo yourself, you would need to add your Bing API key inside ProxyController.cs:

https://github.com/andybeaulieu/BingWebGL/blob/master/BabylonBing/ProxyController.cs

... where it says:

const string _bingMapsKey = " **\* ENTER YOUR BING MAPS API KEY HERE **\* ";

I can't explain why you would see a syntax error inside index.css? It is just a stylesheet and the format looks OK to me?

Hope this helps.
